name: Deploy to Subdomain

on:
  push:
    branches:
      - master

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: FTP Deploy to Subdomain
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ vars.FTP_SERVER }}
          username: ${{ vars.FTP_USERNAME }}
          password: ${{ vars.FTP_PASSWORD }}
          server-dir: /nazib_action/public_html/action/
